deploy:
  stage: deploy
  only:
    - master
  tags:
    - experimental
  variables:
    HOST_PORT: "127.0.0.1:9002"
  script:
    - docker-compose build
    - docker-compose up -d
  environment:
    name: production
    url: https://rights-profile-tool.content-blockchain.creations.de/
